### PR TITLE
Added french translation

### PR DESCRIPTION
**Pull request by Clemovski**
Added file fr_FR.po for France french translation.

Translated somewhat blindly as I don't use Fly-Pie nor Gnome. (I watched Fly-Pie videos.)

I'm still not sure about some expressions, so I would appreciate some guidance.
- What is Marking Mode ? What is the behavior when it is not on ?
- What is Touch Button ? Is it "touch" like in "touch screen" ?

(I am not sure about the animations name either. But there's not much you can do about it I guess.)

### CODE REVIEW

**Comment by Schneegans** [comment]
Wow. Thank you very much for this contribution! It's actually the first time someone translated Fly-Pie without using Weblate, so I am curious whether the changes are incorporated over there automagically. We'll see :). 

Regarding your questions:

> What is Marking Mode ? What is the behavior when it is not on ?

There are basically three interaction modes in Fly-Pie.
* Point-and-Click: The most basic way is to select items by clicking on them or anywhere in the corresponding wedges.
* Marking-Mode: In this mode, you select items by drawing gestures. To do this, you click an item or inside its wedge and drag your mouse. Pausing or making a turn selects the currently dragged item. You could also call this "Gesture Mode". Basically you "draw" the path to an item. It's called "Marking Mode" as this is the term orignially [used by G. P. Kurtenbach](https://damassets.autodesk.net/content/dam/autodesk/www/autodesk-reasearch/Publications/pdf/the-design-and-evaluation.pdf). 
* Turbo-Mode: You can also "draw" gestures while holding <kbd>Ctrl</kbd>, <kbd>Shift</kbd>, or <kbd>Alt</kbd> without having to press your mouse button. This is especially useful when you opened the menu with a shortcut involving such a modifier.

> What is Touch Button ? Is it "touch" like in "touch screen" ?

Jap. Touch as in touch screen. It's shown in the [latest teaser video](https://www.youtube.com/watch?v=BGXtckqhEIk).

Regarding the animation names: I know that French people like to translate everything (:wink:) but in German I just used the English terms. I think it's ok this way.

Again, thank you very much! Once you're happy with the translation, let me know. Then I'll merge it. If you have some time, feel free to install a Linux in a VM an check if everything looks allright! Fedora 35 could be a good GNOME out-of-the-box experience.

**Comment by Clemovski** [comment]
Yes sorry, I read the Readme after finishing the translation.
I'm currently adding some changes on a remote branch. Will merge it when I'm done.

I've installed a VM and noticed some words were broken apart in my translation. Like if spaces were added randomly inside the words. Is this a known behavior ? If no I'll look into it.

Regarding Marking Mode, I'm now torn between readability and credit to M. Kurtenbach. It may help if you could give me a context for marking. Like "marking as in <<following the markings>>". Have a look at wordreference if you have the time : https://www.wordreference.com/enfr/marking

**Comment by Schneegans** [comment]
> I've installed a VM and noticed some words were broken apart in my translation. Like if spaces were added randomly inside the words. Is this a known behavior ? If no I'll look into it.

I haven't encountered something like this. If the issue persists, could you show a screen shot?

> It may help if you could give me a context for marking.

It's kind of difficult for me as I am no native speaker as well. I suspect that he used "mark" to describe a "uniquely shaped line drawn by hand". In his paper, he differentiates two modes: In the _menu mode_ the menu is visible and the user clicks on items. In the  _marking mode_ the menu is invisible and only the line / trace / mark "drawn" by the user is shown. So the term "marking" would refer to the process of drawing these "marks". So I think "marquer quelque chose" in the sense of "faire une marque" could be appropriate. But I do not now to create a proper noun for that in French :D

**Comment by Clemovski** [comment]
Thank you for your insight.
I think this is not perfect but this will do. Hope to see people improve it.
Check if the metadata are OK. And also, should I update resources/credits/translators.json file ?

**Comment by Schneegans** [comment]
The `resources/credits/translators.json` will be populated from weblate data. We will see if your changes are pulled in by weblate properly :wink:

**Comment by Schneegans** [comment]
I think it looks good. There are a few failing checks on Weblate. Do you want to fix them?

https://hosted.weblate.org/projects/fly-pie/core/fr/

**Comment by Clemovski** [comment]
Just updated via Weblate.
It's impressive to see it got everything from the upstream. Also it looks much more practical with the errors and the context pictures. Will make sure to use it next time.

**Pull request merged**
