### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Review by daPhipz — CHANGES_REQUESTED** [review]
Thank you very much for your contribution, again!

Since your last update to the Italian translation, we had a small change to the workflow with translations.

Please have a look at the `Translating Fly-Pie` section of the README - there are some commands that you should run before populating the `it.po` with updated translations.

You may want to have a look at #75 as well, I included some new comments for translators.
Don't update the `.pot` file, though - only the `it.po` file. Updating the `.pot` file would potentially cause merge conflicts.

Thanks again for your contribution, and happy holidays!

**Comment by daPhipz** [comment]
Also, please make sure that the tests are passing, so that your PR can get merged. Thank you! 😊

**Comment by albanobattistella** [comment]
Hi,

I updated my po and not the pot.
I removed the fuzzy and fixed everything.
As for "Time" if it is understood as "how long a certain action took" it is correct Time and I will correct it.
Vediamo dove sono i problemi.

Thanks!

Albano😉
________________________________
Da: daPhipz <notifications@github.com>
Inviato: sabato 26 dicembre 2020 15:25
A: Schneegans/Fly-Pie <Fly-Pie@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [Schneegans/Fly-Pie] Update it.po (#76)


Also, please make sure that the tests are passing, so that your PR can get merged. Thank you! 😊

**Comment by Schneegans** [comment]
Thank you very much!

**Comment by daPhipz** [comment]
...sorry for not responding in time before this PR got merged - I had quite some things around my head the last two weeks.

@albanobattistella Thank you!
Unfortunately, the `.pot` file you based your translation on was outdated. No big problem at all, but you may want to have a look at the [Translating Fly-Pie](https://github.com/Schneegans/Fly-Pie#translating-fly-pie) section of the README. Since your last contribution, things changed a bit ;)

You don't need to rush the translation - once a new version of Fly-Pie is due for release, @Schneegans will ping you, I think!

**Pull request merged**
