### PR TITLE
🚚 Modularize documentation

### PR DESCRIPTION
**Pull request by daPhipz**
As discussed in #79.

I also took the opportunity and split some long lines in half, in order to make the documents more suitable to `git`.

What do you think about the sections? Should it be even more modularized?

### CODE REVIEW

**Comment by Schneegans** [comment]
Thank you for this work! Especially the nav-links at the bottom of each page are quite cumbersome to create... Here are some initial thoughts and observations from my side:
* I think that the README.md should provide a high-level overview of what this repository contains. So I would definitely leave the "About Fly-Pie" section there. I am also unsure about the "Features" list. It feels kind of weird to have a separate page for it. Maybe you can leave them in the README.md and I think of a more compact form to represent them.
* This leaves only one point in "General Information". This is no problem as there will be additional pages in the future!
* I think we should add some pictures to the files as I did for CosmoScout VR, but I can do this later, it's not really in the scope of this PR.
* The CONTRIBUTING file could be lowercase, I think
* In my opinion, the "Table of Contents" heading could be omitted.
* The images are not shown here: https://github.com/daPhipz/Fly-Pie/blob/modular-docs/docs/first-steps.md
* The next-page-link does not work here: https://github.com/daPhipz/Fly-Pie/blob/modular-docs/docs/dbus-interface.md

What do you think?

**Comment by Schneegans** [comment]
I created some pictures you could use for now: [pics.zip](https://github.com/Schneegans/Fly-Pie/files/5780294/pics.zip). There is one banner included which you could add to the top of each page like this:

```html
<p align="center"> 
  <img src ="pics/banner-01.jpg" />
</p>
```

Once this is merged, I will create more banners; one for each page! I also updated the `hr.svg` and added some nav icons you could use like this:

```html
<p align="center"><img src ="pics/hr.svg" /></p>
<p align="center">
  <a href="about.md"><img src ="pics/left-arrow.png" style="height: 1em;"/> About Fly-Pie</a>
  <img src="pics/nav-space.svg"/>
  <a href="../README.md"><img src ="pics/home.png" style="height: 1em;"/> Index</a>
  <img src="pics/nav-space.svg"/>
  <a href="changelog.md">Changelog <img src ="pics/right-arrow.png" style="height: 1em;"/></a>
</p>
```
Maybe they need some tweaking but it helps to create a unique style!

**Comment by daPhipz** [comment]
Thanks for your input!

> I would definitely leave the "About Fly-Pie" section there. I am also unsure about the "Features" list

I agree! Both sections are now back in the original README. :+1:

> I think we should add some pictures to the files as I did for CosmoScout VR

Yes, I thought about adding the GIF from the README to every page, but I thought this was too much animation and would be annoying to look at after some time. Your `pics.zip` looks great!

> The next-page-link does not work here

It should now, since I renamed the file accordingly.

**Comment by Schneegans** [comment]
I merged this and will then tweak the images, some positioning and other minor issues directly in `develop`. Thank you very much!

**Pull request merged**
