### PR TITLE
Update it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by Schneegans** [comment]
Thank you very much! But I think you haven't checked out the `release/v5` branch. There should be some more strings.

**Comment by Schneegans** [comment]
This is the template file for the upcoming release: https://github.com/Schneegans/Fly-Pie/blob/release/v5/po/flypie.pot

**Comment by albanobattistella** [comment]
Hi,
ok thanks..I' working on...
I'll let you know when will be ready.
Regards,
Albano

________________________________
Da: Simon Schneegans ***@***.***>
Inviato: lunedì 5 aprile 2021 21:20
A: Schneegans/Fly-Pie ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [Schneegans/Fly-Pie] Update it.po (#99)


This is the template file for the upcoming release: https://github.com/Schneegans/Fly-Pie/blob/release/v5/po/flypie.pot

**Comment by Schneegans** [comment]
Ok, great! Btw, you should also check the failed test, as it may indicate a problem with the translation. Thank you!

**Comment by Schneegans** [comment]
Hey Albano! Any news on this one? I would really like to release Fly-Pie 5 and this is the last open issue. If you do not have the time to work on this currently, we can also postpone it to the next version. If some strings are not translated, this shouldn't be so bad.

**Comment by albanobattistella** [comment]
Hi Simon,

No problem. I' working on It but I need more time.
If you want to move ön to the 5 is ok for me.
Regards,
Albano
________________________________
Da: Simon Schneegans ***@***.***>
Inviato: domenica 11 aprile 2021 20:20
A: Schneegans/Fly-Pie ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [Schneegans/Fly-Pie] Update it.po (#99)


Hey Albano! Any news on this one? I would really like to release Fly-Pie 5 and this is the last open issue. If you do not have the time to work on this currently, we can also postpone it to the next version. If some strings are not translated, this shouldn't be so bad.

**Comment by Schneegans** [comment]
Ok, thank you! Than I'll release this version now and include the updated translation in the next version.

**Comment by Schneegans** [comment]
Hey Albano, we are currently testing Weblate for managing translations of Fly-Pie. If you want to, you can update the translation there! It should be much easier!

https://hosted.weblate.org/projects/fly-pie/core/

**Comment by albanobattistella** [comment]
Hi Simon,

thank you...will be done!

Regards,
Albano

________________________________
Da: Simon Schneegans ***@***.***>
Inviato: sabato 24 aprile 2021 21:16
A: Schneegans/Fly-Pie ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [Schneegans/Fly-Pie] Update it.po (#99)


Hey Albano, we are currently testing Weblate for managing translations of Fly-Pie. If you want to, you can update the translation there! It should be much easier!

https://hosted.weblate.org/projects/fly-pie/core/

**Comment by Schneegans** [comment]
I'll close this as you will use Weblate for this, I guess :smile:

**Pull request closed without merging**
