### PR TITLE
Test release size

### PR DESCRIPTION
**Pull request by daPhipz**
See #56.

I thought that it would be sensible to always perform the test - even when the build was never intended to be uploaded. That way, one can react quickly and make changes to the code very early.

### CODE REVIEW

**Comment by daPhipz** [comment]
The failed check is normal, since we haven't reduced the zip size on this branch yet :)

**Comment by Schneegans** [comment]
I just merged it to develop. Do you want to merge develop into this branch? Then we will see whether the check succeeds :)

**Comment by daPhipz** [comment]
Ok!

**Comment by daPhipz** [comment]
Yay :tada:

**Comment by Schneegans** [comment]
Great! Thank you!

**Pull request merged**
